# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
      ./snapshot.nix
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "btrfs" "nvme" ];
  boot.supportedFilesystems = [ "btrfs" "nvme" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXOS_ROOT";
      fsType = "btrfs";
      options = [ 
      "subvol=@root"
      "compress=zstd"
      "noatime"
      "ssd"
      ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-label/NIXOS_ROOT";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd" "noatime" "ssd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-label/NIXOS_ROOT";
      fsType = "btrfs";
      options = [ "subvol=@nix" "compress=zstd" "noatime" "ssd" "nosuid" "nodev" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXOS_EFI";
      fsType = "vfat";
    };
  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
