{ config, lib, pkgs, networkConfig, ... }:

let
  hostCfg = networkConfig.hosts.tank;
in
{
  imports = [
    ./disko-config-zfs.nix  # ZFS production config
    # ./hardware-configuration.nix  # Will be generated by nixos-anywhere
    ../../hardware/amd.nix  # AMD GPU support (ROCm)
    ../../system/server
  ];

  networking.hostName = "tank";
  networking.hostId = hostCfg.hostId;
  networking.networkmanager.enable = false;
  system.stateVersion = "25.11";


  # Force static IP configuration - disable ALL DHCP completely
  networking.useDHCP = lib.mkForce false;
  networking.dhcpcd.enable = lib.mkForce false;
  networking.interfaces.${hostCfg.interface} = {
    useDHCP = lib.mkForce false;
    ipv4.addresses = [{
      address = hostCfg.ip;
      prefixLength = networkConfig.prefixLength;
    }];
  };
  networking.interfaces.enp197s0.useDHCP = lib.mkForce false;  # Disable DHCP on second interface

  # Static network configuration
  networking.defaultGateway = networkConfig.gateway;
  networking.nameservers = networkConfig.nameservers;

  # Ensure networking service is enabled
  systemd.services."network-addresses-${hostCfg.interface}".enable = true;
  
  # ZFS tools no longer needed - using Longhorn for storage
  # environment.systemPackages = with pkgs; [
  #   zfs
  # ];

  # Use 6.17 kernel for servers
  boot.kernelPackages = pkgs.linuxPackages_6_17;

  # Override bootloader - servers use ext4, not btrfs subvolumes
  boot.loader.limine.extraConfig = lib.mkForce ''
    TIMEOUT=3
  '';

  # ZFS configuration
  boot.supportedFilesystems = [ "btrfs" "zfs" ];
  boot.zfs.extraPools = [ "tank-fast" "tank-bulk" ];

  # Fix systemd reboot/poweroff commands and prevent GPU black screen
  boot.kernelParams = [
    "systemd.unified_cgroup_hierarchy=1"
    # AMD GPU settings - let driver load but keep console active
    "amdgpu.dc=1"        # Enable Display Core
    "amdgpu.dpm=0"       # Disable dynamic power management
    "consoleblank=0"     # Disable console blanking
  ];

  # Disable Plymouth boot splash (can hide errors)
  boot.plymouth.enable = lib.mkForce false;

  # Enable early KMS for AMD GPU
  boot.initrd.kernelModules = [ "amdgpu" ];

  # Ensure NVMe and disk modules are available in initrd
  boot.initrd.availableKernelModules = [
    "nvme"       # NVMe drive support
    "xhci_pci"   # USB 3.0
    "ahci"       # SATA (for HDDs)
    "usbhid"     # USB HID devices
    "sd_mod"     # SCSI disk support
  ];

  # Ensure systemd can properly handle power management
  systemd.services."systemd-logind".serviceConfig = {
    Restart = "always";
    RestartSec = 0;
  };

  # BTRFS maintenance (for system disk)
  services.btrfs.autoScrub.enable = true;
  services.btrfs.autoScrub.interval = "weekly";

  # ZFS maintenance (for both pools)
  services.zfs.autoScrub.enable = true;
  services.zfs.autoScrub.interval = "monthly";
  services.zfs.autoScrub.pools = [ "tank-fast" "tank-bulk" ];

  # ZFS automatic snapshots
  services.zfs.autoSnapshot = {
    enable = true;
    frequent = 4;   # Keep 4 15-minute snapshots
    hourly = 24;    # Keep 24 hourly snapshots
    daily = 7;      # Keep 7 daily snapshots
    weekly = 4;     # Keep 4 weekly snapshots
    monthly = 12;   # Keep 12 monthly snapshots
  };

  # Fix ZFS mount timeouts during boot
  systemd.services.zfs-mount.enable = true;
  boot.zfs.forceImportRoot = false;
  boot.zfs.forceImportAll = false;

  # Increase timeout for ZFS mounts
  systemd.services."zfs-mount".serviceConfig = {
    TimeoutStartSec = "5min";
  };

  # Configure ZFS legacy mountpoints (prevents systemd mount race)
  # Set mountpoints after pools are imported
  systemd.services.zfs-set-mountpoints = {
    description = "Set ZFS legacy mountpoints for tank pools";
    after = [ "zfs-import.target" ];
    before = [ "zfs-mount.service" ];
    wantedBy = [ "zfs-mount.service" ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
    };
    script = ''
      # tank-fast pool
      ${pkgs.zfs}/bin/zfs set mountpoint=/zfs/gitea tank-fast/gitea

      # tank-bulk pool
      ${pkgs.zfs}/bin/zfs set mountpoint=/zfs/nextcloud tank-bulk/nextcloud
      ${pkgs.zfs}/bin/zfs set mountpoint=/zfs/immich tank-bulk/immich
      ${pkgs.zfs}/bin/zfs set mountpoint=/zfs/paperless tank-bulk/paperless
      ${pkgs.zfs}/bin/zfs set mountpoint=/zfs/backups tank-bulk/backups
    '';
  };

  # Fix network-setup.service failing on avahi-daemon race condition
  # Make it not critical if avahi can't be restarted
  systemd.services.network-setup = {
    serviceConfig = {
      Restart = "no";  # Don't restart if it fails
    };
    unitConfig = {
      # Make this service not block boot if it fails
      # The network is already configured, this just does cleanup
      FailureAction = "none";
    };
  };
}
